export const QuestDefault = {
  id: 0,
  name: "loading",
  desc: "loading",
  issuer: "loading",
  category: "loading",
  rewards_endpoint: "",
  logo: "",
  rewards_img: "",
  rewards_title: "loading",
  rewards_nfts: [],
  img_card: "",
  title_card: "",
  hidden: false,
  disabled: false,
  expiry_timestamp: "loading",
  mandatory_domain: null,
  expired: false,
  rewards_description: null,
  additional_desc: null,
};
